[package]
name = "restack"
version = "0.6.0"
edition = "2021"
description = "Makes git rebase --interactive nicer."

[[bin]]
name = "restack"
path = "src/main.rs"
doctest = false
test = true

[dependencies]
anyhow = "1.0"
argh = "0.1.8"
dirs = "4.0.0"
tempfile = "3.3.0"

[dev-dependencies]
xz2 = "0.1.7"
tar = "0.4.38"
sha2 = "0.10.5"
lazy_static = "1.4.0"

[profile.release]
strip = true
lto = true
