[package]
name = "restack"
version = "0.6.0"
edition = "2021"
description = "Makes git rebase --interactive nicer."

[[bin]]
name = "restack"
path = "src/main.rs"
doctest = false
test = true

[dependencies]
anyhow = "1.0"
argh = "0.1.8"
dirs = "4.0.0"
tempfile = "3.3.0"

[dev-dependencies]
duct = "0.13.5"
indoc = "1.0.7"
lazy_static = "1.4.0"
pretty_assertions = "1.3.0"
restack-testtools = { path = "./testtools" }

[profile.release]
strip = true
lto = true

[workspace]
members = [".", "./testtools"]
