edition = "2021"
version = "Two"

format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
