edition = "2021"
match_block_trailing_comma = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true

# When stable:
# format_code_in_doc_comments = true
# format_strings = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
# reorder_impl_items = true
# version = "Two"
