name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Lin, build, and test
      run: |
        make lint
        go build -v ./...
        go test -race -v ./...
