name: Release

on:
  push:
    tags: ['v*']

  # Support running this manually without uploading to test out the workflow.
  workflow_dispatch:
    inputs:
      version:
        description: "Version we're pretending to release, e.g. 0.6.0"
        required: true
        type: string

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Linux
          - slug: linux-amd64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            extra_pkgs: musl-tools

          - slug: linux-arm64
            target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            linker: aarch64-linux-musl-gcc
            musl-cross: aarch64-linux-musl-cross
            strip: aarch64-linux-musl-strip
            no-build-std: true

          - slug: linux-armv7
            target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
            linker: armv7l-linux-musleabihf-gcc
            musl-cross: armv7l-linux-musleabihf-cross
            strip: armv7l-linux-musleabihf-strip
            no-build-std: true

          # macOS
          - slug: darwin-amd64
            target: x86_64-apple-darwin
            os: macos-latest
          - slug: darwin-arm64
            target: aarch64-apple-darwin
            os: macos-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        target: ${{ matrix.target }}
        profile: minimal
        components: rust-src

    - uses: Swatinem/rust-cache@v2

    - name: Install extra packages
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.extra_pkgs != '' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.extra_pkgs }}

    - name: Install musl cross-compilation toolchain
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.musl-cross != '' }}
      run: |
        mkdir -p "$HOME/.local"
        curl -o /tmp/musl.tgz https://musl.cc/${{ matrix.musl-cross }}.tgz
        tar -xzf /tmp/musl.tgz -C $HOME/.local
        echo "$HOME/.local/${{ matrix.musl-cross }}/bin" >> $GITHUB_PATH

    - name: Configure linker
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.linker != '' }}
      run: |
        mkdir -p .cargo
        cat > .cargo/config <<EOF
        [target.${{ matrix.target }}]
        linker = "${{ matrix.linker }}"
        EOF

    - name: Build (build-std)
      uses: actions-rs/cargo@v1
      if: ${{ !matrix.no-build-std }}
      with:
        command: build
        args: >-
          --target ${{ matrix.target }}
          --locked
          --release
          -Z build-std=std,panic_abort
          -Z build-std-features=panic_immediate_abort

    - name: Build (no-build-std)
      uses: actions-rs/cargo@v1
      if: ${{ matrix.no-build-std }}
      with:
        command: build
        args: >-
          --target ${{ matrix.target }}
          --locked
          --release

    - name: Strip binary
      run: |
        strip=${{ matrix.strip || 'strip' }}
        exe=target/${{ matrix.target }}/release/restack
        echo "Before: $(wc -c < "$exe") bytes"
        "$strip" target/${{ matrix.target }}/release/restack
        echo "After: $(wc -c < "$exe") bytes"

    - name: Prepare archive
      run: |
        tar -cvzf restack-${{ matrix.slug }}.tar.gz \
             -C target/${{ matrix.target }}/release \
             restack

    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: restack-archive
        path: restack-*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download archives
      uses: actions/download-artifact@v3
      with:
        name: restack-archive

    - name: Install parse-changelog
      uses: taiki-e/install-action@v1
      with:
        tool: parse-changelog@0.5.1

    - name: Extract changelog (tag push)
      if:  github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      run: |
        REF=${{ github.ref }}
        VERSION=${REF#refs/tags/v}
        parse-changelog CHANGELOG.md "$VERSION" > ${{ github.workspace }}-CHANGELOG.txt
        echo ::group::CHANGELOG
        cat ${{ github.workspace }}-CHANGELOG.txt
        echo ::endgroup::

    - name: Extract changelog (workflow_dispatch)
      if:  github.event_name == 'workflow_dispatch'
      run: |
        VERSION=${INPUT_VERSION#v}
        parse-changelog CHANGELOG.md "$VERSION" > ${{ github.workspace }}-CHANGELOG.txt
        echo ::group::CHANGELOG
        cat ${{ github.workspace }}-CHANGELOG.txt
        echo ::endgroup::
      env:
        INPUT_VERSION: ${{ inputs.version }}

    - name: Publish Release
      if:  github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: 'restack-*.tar.gz'
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Publish Homebrew tap
    #   uses: Justintime50/homebrew-releaser@v1
    #   with:
    #     homebrew_owner: abhinav
    #     homebrew_tap: homebrew-tap
    #     formula_folder: .
    #     github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
    #     install: 'bin.install restack'
    #     test: '#{bin/restack --version'
    #     target_darwin_amd64: true
    #     target_darwin_arm64: true
    #     target_linux_amd64: true
    #     target_linux_arm64: true

    # env:
    #   AUR_KEY: ${{ secrets.AUR_KEY }}
