name: Release

on:
  push:
    tags: ['v*']

jobs:

  build:
    runs-on: ${{ matrix.os }}

    # Only release pushes of tags starting with v.
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        include:
          # Linux
          - {os: ubuntu-latest, target: x86_64-unknown-linux-musl}
          - {os: ubuntu-latest, target: aarch64-unknown-linux-musl}
            # - {os: ubuntu-latest, target: armv7-unknown-linux-musleabihf}
          - {os: ubuntu-latest, target: arm-unknown-linux-musleabihf}
          - {os: macos-latest, target: x86_64-apple-darwin}
          - {os: macos-latest, target: aarch64-apple-darwin}
          - {os: ubuntu-latest, target: x86_64-pc-windows-gnu, bin: "restack.exe"}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
        profile: minimal
        target: ${{ matrix.target }}
        override: true

    - uses: Swatinem/rust-cache@v2

    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: 0.9.1

    - name: Install cargo-zigbuild
      run: cargo install cargo-zigbuild

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: zigbuild
        args: --target ${{ matrix.target }} --release

    - name: Prepare archive
      run: |
        tar -cvzf restack-${{ matrix.target }}.tar.gz \
             -C target/${{ matrix.target }}/release \
             ${{ matrix.bin || 'restack' }}

    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: restack-archive
        path: restack-*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:

    - name: Download archives
      uses: actions/download-artifact@v3
      with:
        name: restack-archive

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: 'restack-*.tar.gz'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # env:
    #   AUR_KEY: ${{ secrets.AUR_KEY }}
    #   HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
